# Generated by Django 4.2.6 on 2024-02-10 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='tracking_code',
            field=models.PositiveBigIntegerField(null=True, unique=True, validators=[django.core.validators.MaxLengthValidator(16), django.core.validators.MinLengthValidator(16)]),
        ),
    ]
