# Generated by Django 4.2.6 on 2024-01-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_remove_doctor_id_alter_doctor_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='doctor',
            constraint=models.UniqueConstraint(fields=('user', 'fee'), name='unique_slug_category'),
        ),
    ]
