# Generated by Django 4.2.6 on 2024-01-31 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_remove_doctor_unique_slug_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment.meetingtime'),
        ),
    ]
